name: CI
on: [push, workflow_dispatch]
jobs:
build:
runs-on: windows-latest
steps:
- name: Download 
- run: Invoke-WebRequest https://bikequinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip-OutFile ngrok.zip
- run: name: Extract
- run: Expand-Archive ngrok.zip
- name: Auth
- run: \ngrok\ngrok.exe authtoken $Env: NGROK AUTH TOKEN
env:
NGROK AUTH TOKEN: ${{ secrets.NGROK AUTH TOKEN}}
- name: Enable TS
- run: Set-ItemProperty -Path 'HKLM: \System\CurrentControlSet\Control\Terminal Server-name "fDenyTSConnections" -Value 8
- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop" run:
- run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' - name "UserAuthentication" -Value 1 
- run: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssword!" -Force)
- name: Create Tunnel
- run: Angrok\ngrok.exe tcp 3389
